AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serverless Events API

Resources:

  EventsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Events
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: event_id
          AttributeType: S
      KeySchema:
        - AttributeName: event_id
          KeyType: HASH

  EventsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: events-api
      Runtime: python3.11
      Handler: app.main.handler
      CodeUri: ../
      MemorySize: 128
      Timeout: 10
      Policies:
        - DynamoDBCrudPolicy:
            TableName: Events
      Events:
        Api:
          Type: HttpApi
          Properties:
            Path: /{proxy+}
            Method: ANY
      Environment:
        Variables:
          TABLE_NAME: Events