name: Deploy SAM App

on:
push:
branches:
- master
workflow_dispatch:

permissions:
id-token: write
contents: read

env:
AWS_REGION: ap-south-2
STACK_NAME: test-event-stack

jobs:
deploy:
runs-on: ubuntu-latest

```
steps:
  - name: Checkout repository
    uses: actions/checkout@v4

  - name: Set up Python 3.13
    uses: actions/setup-python@v5
    with:
      python-version: '3.13'

  - name: Configure AWS credentials from GitHub OIDC
    uses: aws-actions/configure-aws-credentials@v4
    with:
      role-to-assume: arn:aws:iam::233636046266:role/github-actions-events-api-role
      aws-region: ${{ env.AWS_REGION }}

  - name: Setup AWS SAM
    uses: aws-actions/setup-sam@v2

  - name: SAM build
    run: sam build --template-file infra/template.yaml --no-cached

  - name: SAM deploy
    run: |
      sam deploy \
        --template-file .aws-sam/build/template.yaml \
        --stack-name $STACK_NAME \
        --region $AWS_REGION \
        --capabilities CAPABILITY_NAMED_IAM \
        --resolve-s3 \
        --parameter-overrides \
          StageName=prod \
          ProjectName=test-events-api \
          EventsTableName=eventsv1 \
          CognitoDomainPrefix=events-api-full-auth-demo \
          CallbackUrl=https://oauth.pstmn.io/v1/callback \
          LogoutUrl=https://oauth.pstmn.io/v1/callback \
          GitHubOrg=hy3333 \
          GitHubRepo=aws-serverless-events-api \
          GitHubBranch=master \
          CreateGitHubOidcProvider=true \
          ExistingGitHubOidcProviderArn=arn:aws:iam::233636046266:oidc-provider/token.actions.githubusercontent.com \
        --no-confirm-changeset \
        --no-fail-on-empty-changeset
```
